// Echo currently has an English interface and Russian native-language cues.
// Keep onboarding copy together so another UI locale can use the same keys.
export const tutorOnboardingCopy = {
  title: "Make Tutor work for you",
  intro: "Four quick questions and one small practice task. You can ask Tutor anything about the language, or ask for a topic, a plan or a different way to practise.",
  funnel: [
    ["Tutor", "Create useful cards together. Check the drafts before saving. If you are unsure what to do next, ask Tutor."],
    ["Listen & Repeat", "Listen, repeat aloud and practise pronunciation. Like adds a card to Liked. To Recall is a separate action that makes it available in Active Recall sooner."],
    ["Active Recall", "Remember before revealing the answer. Choose Again, Hard, Good or Easy for how easily you remembered, rather than how much you like the card. FSRS schedules the next recall."],
    ["Tutor", "Use your cards in changed phrases, questions, new situations and conversation. Ask about the grammar when you need it."],
    ["Learned", "Work towards recalling, understanding, pronouncing and using the phrase in life. Mark a card Learned when you are ready; you can return it to practice later."],
  ],
  contentChoice: "Use Recommended, Topics or Liked to choose content, or go straight to Tutor. Listen & Repeat also lets you choose individual cards.",
  questions: ["How does the language feel right now?", "Where will you use it?", "What would you like to talk about?", "How would you like to practise?"],
  comfort: ["I can hardly say anything", "I can say simple things with help", "I can communicate and choose my direction"],
  goals: ["Everyday life", "Travel", "Work", "Moving abroad", "Relationships", "An exam"],
  preferences: ["Guide me fully", "Offer me choices", "Let me choose"],
  modeLabels: { beginner: "More help", intermediate: "Together", advanced: "Independently" },
  descriptions: { beginner: "I will give you short steps and examples. As you get more comfortable, we can give you more freedom.",
    intermediate: "We will choose useful directions together. I will start with small hints and give examples when you need them.",
    advanced: "You can choose the topic, method or plan. I will follow your direction and help with important language gaps." },
  task: "Write two or three simple sentences about yourself or a situation you want to handle. This is a starting point, not a test. Russian is fine if you need it.",
  modelIntro: "You can start with these patterns, or write your own version in the learning language or Russian:",
  models: { en: "I live in… I like… I want to…", lv: "Es dzīvoju… Man patīk… Es vēlos…", no: "Jeg bor… Jeg liker… Jeg vil…",
    vi: "Tôi sống ở… Tôi thích… Tôi muốn…", id: "Saya tinggal di… Saya suka… Saya ingin…", de: "Ich wohne… Ich mag… Ich möchte…" },
  skip: "Skip for now", back: "Back", next: "Continue", start: "Start my first exercise", saving: "Saving…",
  error: "Could not save this step. Your answer is still here. Try again.",
  startingTask: "A small starting task", ready: "Your Tutor is ready", journey: "Echo learning journey",
  questionProgress: (step: number) => `Question ${step} of 4`, otherGoal: "Another goal", usefulInterests: "Interests or useful situations",
  sentences: "Your sentences", needExample: "I need an example",
  opening: "Opening Tutor…", loadingError: "Tutor settings could not load. You can keep chatting.", retry: "Retry",
  settings: "Tutor settings", support: "Support", nativeHelp: "Native-language help", inherit: "Follow my support style",
  nativeHelpLabels: { allowed: "Allowed", when_needed: "When needed", on_request: "On request" },
  goalsLabel: "Goals", interestsLabel: "Interests", saveGoals: "Save goals and interests", reset: "Reset custom support settings", end: "End session",
  saved: "Saved to your account.", settingsError: "Could not save Tutor settings. Try again.",
  summaryError: "Your chat is safe. The session summary could not be saved; try End session again.",
  finishError: "Your chat is safe. Could not end the session; try again.",
} as const;
